version: '3'
services:
  some-rabbit:
    image: rabbitmq:3-management
    container_name: some-rabbit
    hostname: some-rabbit
    network_mode: "bridge"
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "15672:15672"
      - "5672:5672"